# Generated by Django 6.0.5 on 2026-05-15 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='License number must consist of 8 characters: first 3 uppercase letters and last 5 digits.', regex='^[A-Z]{3}\\d{5}$')]),
        ),
    ]
